#!/bin/sh

set -ex

apt-get update
sudo apt-get install -y -q apt-transport-https
rm -rf /var/cache/apt/archives/*

lsb_dist="$(lsb_release -si)"
dist_version=''
dist_version="$(lsb_release --codename | cut -f2)"
lsb_dist="$(echo "$lsb_dist" | tr '[:upper:]' '[:lower:]')"

apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
mkdir -p /etc/apt/sources.list.d
echo deb https://apt.dockerproject.org/repo ${lsb_dist}-${dist_version} main > /etc/apt/sources.list.d/docker.list
apt-get update
apt-get install -y -d "docker-engine=$1*"